### ISSUE TITLE
Causes "...can only be used in typescript files" errors within `.ts` and `.tsx` files

### ISSUE THREAD

**Issue by lunelson** [mdx-js/vscode-mdx#282] opened 2023-01-22 16:52 UTC
Type: <b>Bug</b>

These errors appeared this afternoon and this extension was identified as the cause via the "extension bisect" process

Extension version: 1.1.0
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:05:47.808Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 3, 3|
|Memory (System)|32.00GB (2.80GB free)|
|Process Argv|--crash-reporter-id 3eeb5f38-28fb-4ce7-b7cf-15288234da3e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30647091
89544117:30613380
2i9eh265:30646982

```

</details>

**Comment by remcohaszing** [comment] 2023-01-22 20:26
Thanks for reporting, but this is a duplicate of #270

**Closed by remcohaszing** 2023-01-22 20:26 UTC
